# Generated by Django 3.1.2 on 2020-10-28 01:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30, unique=True)),
                ('supplier_name', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_description', models.CharField(max_length=40)),
                ('item_color', models.CharField(max_length=10)),
                ('item_date', models.DateTimeField()),
                ('item_category', models.CharField(max_length=40)),
                ('item_subcategory', models.CharField(max_length=40)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('item_current_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=100000000), max_digits=100000000)),
                ('item_on_sale', models.BooleanField(default=False)),
                ('item_sku', models.CharField(max_length=5, unique=True)),
                ('item_quantity', models.IntegerField()),
                ('item_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_model.brand', to_field='brand_name')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('item_brand'), nulls_last=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('item_name'), nulls_last=True)],
            },
        ),
    ]
