# Generated by Django 3.1.2 on 2020-12-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_abbre',
            field=models.CharField(default='DRM', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
