# Generated by Django 3.1.2 on 2020-11-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_subcategory',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
