# Generated by Django 3.1.2 on 2020-11-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_model', '0002_auto_20201105_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_size',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
