# Generated by Django 3.1.2 on 2020-11-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_model', '0003_item_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_color_code',
            field=models.CharField(default='NON', max_length=3),
            preserve_default=False,
        ),
    ]
