# Generated by Django 3.1.2 on 2020-11-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_model', '0004_item_item_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_season',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
