# Generated by Django 3.1.2 on 2020-10-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(max_length=4, unique=True)),
                ('location_to', models.CharField(max_length=3)),
                ('location_from', models.CharField(max_length=3)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_completed', models.DateField(null=True)),
                ('complete_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TransferItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer_model.transfer', to_field='transfer_id')),
                ('transfer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_model.item', to_field='item_sku')),
            ],
        ),
    ]
