# Generated by Django 3.1.2 on 2020-10-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_model', '0001_initial'),
        ('item_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=5, unique=True)),
                ('order_date', models.DateField()),
                ('order_fulfilled', models.BooleanField(default=False)),
                ('order_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_model.customer', to_field='customer_id')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_model.order', to_field='order_id')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_model.item')),
            ],
        ),
    ]
