# Generated by Django 3.1.2 on 2020-12-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_model', '0002_brand_brand_abbre'),
        ('order_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_model.item', to_field='item_sku'),
        ),
    ]
